// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPmRQMuCOCc15XESFfTabjbp3Ull-Feig',
    appId: '1:68434851440:web:6c4d5723ef1697c69866b5',
    messagingSenderId: '68434851440',
    projectId: 'clothotag',
    authDomain: 'clothotag.firebaseapp.com',
    storageBucket: 'clothotag.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApVnaDmYD0SHXFX9B-DQIbwMN_XrsC4zY',
    appId: '1:68434851440:android:b14b3acaef598e269866b5',
    messagingSenderId: '68434851440',
    projectId: 'clothotag',
    storageBucket: 'clothotag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRciy721iflCsy70P3OgKnU6-hBTUWcFs',
    appId: '1:68434851440:ios:223403ccc6a451bc9866b5',
    messagingSenderId: '68434851440',
    projectId: 'clothotag',
    storageBucket: 'clothotag.firebasestorage.app',
    iosBundleId: 'com.clothotag.clothotag',
  );
}
